### ISSUE TITLE
PHMSD - wrong energy?

### ISSUE THREAD

**Issue by michaelstreif** [linusjoonho/ipie#120]
Hi,

In the example https://github.com/linusjoonho/ipie/blob/main/examples/generic/04-phmsd_wicks/gen_msd.py, you use a CASSCF calculation and pick SDs with high coefficient to enlarge the trial state.  The integrals/Cholesky vectors are represented in the CASSCF basis. I have troubles understanding which walker state is created here:

> psi0a = eigv[::-1, occa[0]].copy()
> psi0b = eigv[::-1, occb[0]].copy()
> nocca = mol.nelec[0]
> noccb = mol.nelec[1]
> nbsf = psi0a.shape[0]
> psi0a += 1e-1 * numpy.random.randn(nocca * nbsf).reshape(nbsf, nocca)
> psi0b += 1e-1 * numpy.random.randn(noccb * nbsf).reshape(nbsf, noccb)
> psi0 = [psi0a, psi0b]

Especially, why are you adding random elements to the walker state?

To understand a bit better what's going on I changed from CASSCF to CASCI and set the number of determinants to include to one (`ndets = 1`) and used the full space as active space (for H4 in STO-3g). In this case, I would expect that the trial state is just again the RHF state and that the algorithm starts at the RHF energy. However, the energy at the zero-th step differs from that. If I don't specify an initial walker (`init=None`), I get the energy I would expect. 

Further questions: 
- As far as I understood the code, you are not using spin-dependent integrals. Thus, when UHF is used, you use the mo_coeff of the alphas to transform the integrals. Is there a possibility to use UHF with the PHMSD? 

Minor comments: 
- In line 35, enuc has to be added. 
- Why is 'uhf' given as argument 93? i) it was not used and ii) it seems the code never uses the argument. 

Thanks! :-)

**Comment by fdmalone** [comment]
Hi! Thanks for looking through the examples. So this example is a bit out of date for several reasons:

1. the random noise / unusual walker initialization was due to an old naive implementation of MSD which would have zero overlap with all but the reference determinant and this would cause the code to crash. In projector MC we're free to choose the initial walker wavefunction (assuming it's not orthogonal to the ground state) so a workaround was to make it other than the reference (in this case) HF determinant.
2. if init=None the HF wavefunction will be chosen by default so you should get the HF energy. For init=something_else it will compute <psi_T| H | psi_0> which should be different in general.
3. We don't permit spin dependent integrals and UHF is not supported for PHMSD. For UHF SD calculations you can either use the alphas like you said or we sometimes use canonical orthogonalization to write the Hamiltonian in an orthogonalized AO basis (ortho_ao).
4. Thanks for that, it's likely we'll do a rewrite of the examples.
5. This is marked for deprecation it does nothing you're right. Generally speaking we adopt the qmcpack file format for wavefunction and integrals, and these helper utilities are a bit clunky. We'll tidy this up and we plan on potentially adopting a new format in the future.
